name: CI

on:
  # Allow the workflow to be triggered by manual dispatch, push, or pull request events
  workflow_call:
  # Trigger the workflow on manual dispatch or push/pull request events
  workflow_dispatch:
  # Trigger the workflow on push or pull request events to the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t my-vulnerable-app:ci .

      - name: Run Docker container (10s)
        run: |
          docker run -d --name my-vulnerable-app-test -p 8000:8000 my-vulnerable-app:ci
          sleep 10
          docker ps -a
          docker logs my-vulnerable-app-test

      - name: Stop and remove container
        if: always()
        run: |
          docker stop my-vulnerable-app-test || true
          docker rm my-vulnerable-app-test || true

      - name: Run Security SCA (sec-sca)
        uses: ./.github/workflows/sec-sca.yml